### PR TITLE
Fix various build and test bugs on pre-5.10

### PR DESCRIPTION
**Pull request by arc**
Plus a test-count bug that affects all Perl versions.

### CODE REVIEW

**Comment by arc** [comment]
The changes I've just added to this pull request are no longer just related to build and test bugs; it seemed like it would be easier for you if I rolled them all up together.

The additional changes are:
- `is_plain_ref`, `is_plain_formatref`, and `is_plain_refref` now exist
- All the existing routines incorrectly returned true for ref-ref values; now fixed
- I've changed `is_scalarref` and `is_plain_scalarref` to return false for ref-ref values

That last one represents a change in documented behaviour. The rationale for it is two-fold. First, callers that want to decide how to handle inputs based on their reference type will usually want to treat a ref-ref and a scalar-ref differently. Secondly, this more closely matches the behavior of the `ref` builtin and of `reftype`, which both report a ref-ref as "REF" rather than "SCALAR".

There are still no `is_plain_ioref` or `is_plain_regexpref` functions: I/O and regexp refs are always blessed, so they would always return false. If you think it best, I'm happy to add trivial functions with those names, though.

**Comment by xsawyerx** [comment]
Thank you for all the work.

I agree with your comments on both `scalarref`  vs. `refref` and `ioref` and `regexpref`.

I will merge these and release a version and blog about it. The next step would be the blessed and _any_ functions. Bit by bit. :)

**Comment by arc** [comment]
More changes:
- Remove all the code duplication
- Massively extend the test suite
- Another behaviour change for `is_scalarref`: it no longer returns true for `qr/./` or `\*GLOB`
- All the `is_blessed_*ref` routines now exist 😄 

The rationale for this `is_scalarref` behaviour change is the same as for the last one.

**Comment by xsawyerx** [comment]
@arc, this is so awesome! I worked today on doing some of this. It'd be my pleasure to `reset --hard` and merge your additions. Thanks for working on this!

**Comment by arc** [comment]
Sorry, I should have told you I was still working on this.

One more commit, anyway: the ordinary XS routines were failing to do error detection.

**Comment by xsawyerx** [comment]
Merged the new commits too. Thank you. :)

Please send future commits on a different branch. I'm also adding you to collaborators.

**Pull request closed without merging**
